set(_CATKIN_CURRENT_PACKAGE "nuestro_abb_irb120")
set(nuestro_abb_irb120_VERSION "0.2.0")
set(nuestro_abb_irb120_MAINTAINER "MoveIt Setup Assistant <assistant@moveit.ros.org>")
set(nuestro_abb_irb120_PACKAGE_FORMAT "1")
set(nuestro_abb_irb120_BUILD_DEPENDS "urdf_serp")
set(nuestro_abb_irb120_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "urdf_serp")
set(nuestro_abb_irb120_BUILDTOOL_DEPENDS "catkin")
set(nuestro_abb_irb120_BUILDTOOL_EXPORT_DEPENDS )
set(nuestro_abb_irb120_EXEC_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "urdf_serp")
set(nuestro_abb_irb120_RUN_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "urdf_serp")
set(nuestro_abb_irb120_TEST_DEPENDS )
set(nuestro_abb_irb120_DOC_DEPENDS )
set(nuestro_abb_irb120_DEPRECATED "")