set(_CATKIN_CURRENT_PACKAGE "abb_irb120_gazebo")
set(abb_irb120_gazebo_VERSION "0.0.1")
set(abb_irb120_gazebo_MAINTAINER "Mark Culleton (Trinity College Dublin) <culletom@tcd.ie>")
set(abb_irb120_gazebo_PACKAGE_FORMAT "1")
set(abb_irb120_gazebo_BUILD_DEPENDS )
set(abb_irb120_gazebo_BUILD_EXPORT_DEPENDS "abb_irb120_support" "gazebo" "gazebo_ros" "gazebo_ros_control" "gazebo_ros_pkgs" "joint_state_controller" "position_controllers" "joint_trajectory_controller" "robot_state_publisher" "ros_controllers")
set(abb_irb120_gazebo_BUILDTOOL_DEPENDS "catkin")
set(abb_irb120_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(abb_irb120_gazebo_EXEC_DEPENDS "abb_irb120_support" "gazebo" "gazebo_ros" "gazebo_ros_control" "gazebo_ros_pkgs" "joint_state_controller" "position_controllers" "joint_trajectory_controller" "robot_state_publisher" "ros_controllers")
set(abb_irb120_gazebo_RUN_DEPENDS "abb_irb120_support" "gazebo" "gazebo_ros" "gazebo_ros_control" "gazebo_ros_pkgs" "joint_state_controller" "position_controllers" "joint_trajectory_controller" "robot_state_publisher" "ros_controllers")
set(abb_irb120_gazebo_TEST_DEPENDS )
set(abb_irb120_gazebo_DOC_DEPENDS )
set(abb_irb120_gazebo_DEPRECATED "")